feat: update babel with publicKey and removed unused methods/packages
crherman7/rechunk pull request #13
Opened 2024-06-09 19:07 UTC by devs9

## Scope

closes ISSUE - #8 

## Implementation

Updated the babel plugin to provide code generation for adding the public key and `global` object to the `ChunkManager`. If someone would like to overwrite it they could then do this via the `ReChunk.addResolver` function. Also, the default function `resolver`/`fetchChunk` is provided, which can be rewritten with `ReChunk.addResolver` as well.

Updated signature of `ReChunk.addResolver` function, now it is an object with optional configuration parameters.

Updated signature for verify bridge method. added `publicKeyStr` property as a fourth argument for both platform.

Unnecessary method's and package's have been removed, the cli `sync` command and the native properties in the example app has been removed as well.

## Screenshots

<details>
  <summary>ios</summary>

  https://github.com/crherman7/rechunk/assets/45544661/289f1be9-516a-4a8a-8036-f675749f0945
</details>

<details>
  <summary>android</summary>
  
  https://github.com/crherman7/rechunk/assets/45544661/b1a2370c-6d12-4e17-bd04-ea13c6c9aef6
</details>

## How to Test

## Emoji Guide

**For reviewers: Emojis can be added to comments to call out blocking versus non-blocking feedback.**

E.g: Praise, minor suggestions, or clarifying questions that don’t block merging the PR.

> 🟢 Nice refactor!

> 🟡 Why was the default value removed?

E.g: Blocking feedback must be addressed before merging.

> 🔴 This change will break something important

| | | |
| --- | --- | --- |
| Blocking | 🔴 ❌ 🚨 | RED |
| Non-blocking | 🟡 💡 🤔 💭 | Yellow, thinking, etc |
| Praise | 🟢 💚 😍 👍 🙌 | Green, hearts, positive emojis, etc |

2024-06-11 14:23 UTC, crherman7 requested changes

2024-06-11 14:23 UTC, crherman7 commented on src/babel/index.ts
> +        if (t.isIdentifier(node.id, {name: 'ChunkManager'})) {
🟡 this just came to mind but let's make sure that tsup minify does not remove these names - sometimes minifiers can remove in favor of shorter ref names

2024-06-11 14:23 UTC, crherman7 commented on src/babel/index.ts
> +          body.forEach(property => {
🤔 this is fine to do, but it may be more efficient to create additional visitor functions that you would traverse so you don't have to do it manually - I can explain more

2024-06-11 14:23 UTC, crherman7 commented on src/react-native/ChunkManager.ts
> +    if (verify) {
❌ need to check actual value since it's a boolean

```
if (verify !== undefined) {
  ...
}
```

2024-06-11 14:23 UTC, crherman7 commented on src/react-native/ChunkManager.ts
> +  protected resolver: ResolverFunction = async chunkId => {
🙌 beautiful

2024-06-11 14:23 UTC, crherman7 commented on ios/ReChunk.swift
> +    func verify(_ data: String, hash: String, signature: String, publicKeyStr: String, resolve: RCTPromiseResolveBlock, reject: RCTPromiseRejectBlock) -> Void {
😀 this will be much better!

2024-06-11 14:23 UTC, crherman7 commented
awesome job so far on this - this is a great step forward on leaning out code! great work! 🚀

2024-06-12 21:33 UTC, devs9 commented on src/babel/index.ts
> +          body.forEach(property => {
Thanks, that's a great idea, I didn't know about that

2024-06-12 21:34 UTC, devs9 commented on src/babel/index.ts
> +        if (t.isIdentifier(node.id, {name: 'ChunkManager'})) {
that's what happened, good catch 👍

2024-06-13 00:06 UTC, crherman7 requested changes

2024-06-13 00:06 UTC, crherman7 commented on src/babel/index.ts
> +          traverse({
This is just about there but reading the handbook I found that nesting visitors like this I.e. in the same visitor can be very costly - it's better to create a new visitor outside the structure: https://github.com/kentcdodds/babel-plugin-handbook/blob/master/README.md#optimizing-nested-visitors let me know if that doesn't make sense.

2024-06-14 20:36 UTC, crherman7 approved these changes
Awesome job! 💚

2024-06-14 20:38 UTC, merged