feat: rechunk dev-server discovery
crherman7/rechunk pull request #47
Opened 2024-09-20 18:20 UTC by crherman7

## Scope

[closes TICKET-###](https://link-to-your-ticket)

## Implementation

## Screenshots

<details>
  <summary>ios</summary>

  
</details>

<details>
  <summary>android</summary>
  
  
</details>

## How to Test

## Emoji Guide

**For reviewers: Emojis can be added to comments to call out blocking versus non-blocking feedback.**

E.g: Praise, minor suggestions, or clarifying questions that don’t block merging the PR.

> 🟢 Nice refactor!

> 🟡 Why was the default value removed?

E.g: Blocking feedback must be addressed before merging.

> 🔴 This change will break something important

| | | |
| --- | --- | --- |
| Blocking | 🔴 ❌ 🚨 | RED |
| Non-blocking | 🟡 💡 🤔 💭 | Yellow, thinking, etc |
| Praise | 🟢 💚 😍 👍 🙌 | Green, hearts, positive emojis, etc |

2024-09-20 18:21 UTC, crherman7 commented on packages/babel-plugin/src/index.ts
> +      it.cmd.includes('rechunk dev-server') &&
magic string

2024-09-20 18:21 UTC, crherman7 commented on packages/babel-plugin/src/index.ts
> +      (it.cmd.startsWith('node ./node_modules') ||
magic string

2024-09-20 18:21 UTC, crherman7 commented on packages/cli/src/cmds/dev-server.ts
> +    const port = '56748';
magic string

2024-09-20 18:21 UTC, crherman7 commented on packages/babel-plugin/src/index.ts
> +              ? t.stringLiteral('http://localhost:56748')
magic string

2024-09-22 19:17 UTC, devs9 requested changes
🟢 Awesome job! very useful feature 👍 
🟡 but there are some packages we can remove

2024-09-22 19:17 UTC, devs9 commented on packages/cli/src/cmds/dev-server.ts
> -import prettier from 'prettier';
🟡 after these updates, we can remove `prettier` and `get-port` from the `@crherman7/rechunk-cli` package.json

2024-09-22 19:17 UTC, devs9 commented on packages/babel-plugin/src/index.ts
> +  const workspaceDir = findWorkspaceDir(cwd());
🟢 great helpers methods 👍

2024-09-23 21:52 UTC, crherman7 commented on packages/cli/src/cmds/dev-server.ts
> -import prettier from 'prettier';
awesome catch!

2024-09-24 13:10 UTC, devs9 approved these changes
💚  Awesome job!! Looks great 👍

2024-09-24 13:11 UTC, merged